[project]
name = "leetcode"
version = "0.1.0"
description = "Solutions to leetcode problems"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.3",
]
